import turtle
grass = turtle.Turtle()
grass.hideturtle()
sky = turtle.Turtle()
sky.hideturtle()
house = turtle.Turtle()
house.hideturtle()
tree = turtle.Turtle()
tree.hideturtle()
sun = turtle.Turtle()
sun.hideturtle()
wn = turtle.Screen()
skycol = ['add8e6','b5d8e5','bdd8e4','c5d8e3','cdd8e3','d6d8e2','ded8e1','e6d8e1','eed8e0','f6d8df','ffd9df']

wn.reset()
wn.setworldcoordinates(-300,-200,700,400)

def drawsky():
  sky.showturtle()
  sky.speed(100)
  sky.color('#e5e5ff')
  sky.pensize(100)
  sky.setpos(-300, -200)
  for i in skycol:
     temp = '#' + i
     sky.color(temp)
     sky.forward(1100)
     sky.left(90)
     sky.forward(25)
     sky.left(90)

     sky.color(temp)
     sky.forward(1100)
     sky.right(90)
     sky.forward(25)
     sky.right(90)
  sky.hideturtle()

def drawgrass():
  grass.showturtle()
  grass.pu()
  grass.speed(100)
  grass.color("green")
  grass.setx(-350)
  grass.seth(0)
  for y in [-180, -185, -190, -195]:
    grass.setpos(-290, y)
    grass.pd()
    for i in range(39):
      grass.seth(45)
      grass.fd(20)
      grass.seth(315)
      grass.fd(20)
    grass.pu()
  grass.hideturtle()

def drawhouse():
  house.speed(100)
  house.showturtle()
  house.pu()
  house.color("brown")
  house.setpos(270, -178)
  house.pd()
  house.seth(90)
  house.fillcolor("#4DCC04")
  house.begin_fill()
  for i in range(4):
    house.fd(250)
    house.rt(90)
  house.end_fill()
  house.pu()
  house.setpos(270, 70)
  house.seth(60)
  house.pd()
  house.fillcolor("#CC5604")
  house.begin_fill()
  for i in range(3):
    house.fd(250)
    house.rt(120)
  house.end_fill()
  house.pu()
  house.setpos(520, 70)
  house.seth(0)
  house.pd()
  house.fillcolor("#DA0808")
  house.begin_fill()
  house.fd(270)
  house.lt(120)
  house.fd(250)
  house.lt(60)
  house.fd(270)
  house.end_fill()
  house.pu()
  house.setpos(790, 70)
  house.seth(270)
  house.pd()
  house.fillcolor("#F82F2F")
  house.begin_fill()
  house.fd(250)
  house.rt(90)
  house.fd(270)
  house.rt(90)
  house.fd(250)
  house.end_fill()
  house.pu()
  house.setpos(350, -178)
  house.seth(90)
  house.pd()
  house.fillcolor("#953400")
  house.begin_fill()
  house.fd(150)
  house.rt(90)
  house.fd(100)
  house.rt(90)
  house.fd(150)
  house.end_fill()
  house.hideturtle()

def drawtree():
  tree.showturtle()
  tree.color("green")
  tree.speed(100)
  tree.pu()
  tree.setpos(-100, -180)
  tree.seth(90)
  tree.pd()
  def draw(l):
    if(l<10):
      return
    else:
      tree.fd(l)
      tree.lt(30)
      draw(3*l/4)
      tree.rt(60)
      draw(3*l/4)
      tree.lt(30)
      tree.backward(l)
  draw(100)
  tree.hideturtle()

def drawsun():
  sun.showturtle()
  sun.speed(100)
  sun.pu()
  sun.setpos(-100, 200)
  sun.color("orange")
  sun.pd()
  sun.begin_fill()
  sun.circle(50,360)
  sun.end_fill()
  for i in range(18):
    sun.right(90)
    sun.penup()
    sun.forward(10)
    sun.pendown()
    sun.forward(10)
    sun.penup()
    sun.backward(20)
    sun.left(90)
    sun.circle(50,20)
  sun.hideturtle()
    



drawsky()
drawgrass()
drawhouse()
drawtree()
drawsun()
wn.exitonclick()